### ISSUE TITLE
Messenger v167

### ISSUE THREAD

**Issue by haniag** [karek314/hexbytescanner-hooks#2]
I tried all three json files, but all provide the same result that patch address has not been found. This was done on FB Messenger v167. Any advice? I can send binary for analysis.

**Comment by karek314** [comment]
Hi,
1.1.0 pattern was far from good.
https://github.com/karek314/hexbytescanner-hooks/commit/851009c4cecf10d0440401a20c9f09127eb55b90
Fixed.

**Comment by haniag** [comment]
Thanks for your effort, but still get "can't patch because patch address has not been found".

**Comment by karek314** [comment]
Maybe you are patching wrong binary, did you tried any of frameworks ?

**Comment by haniag** [comment]
I tried app and its frameworks. It could be that I am doing something wrong, or they are using something different for this version. Either way, you can try yourself: https://we.tl/k3sEF5AnVa

**Comment by karek314** [comment]
Then you might be trying scan fat binary instead of thin. Give a try unpacking with https://github.com/karek314/HandyIPAPatcher

**Comment by level02** [comment]
I have the same problem, I hooked the fat binary framework, I repack but didn't work the pinning. I hooked the thin binary but again didn't work the pinning. I don't know if the problem was when I repacked, I used the 3 commands from replace_bin.sh

**Comment by karek314** [comment]
Maybe something changed or this is no longer based on openssl, i will take a look when I have some free time
